version: '3'
services:
  web:
    image: vsware-frontend-interview
    build: .
    command: yarn start
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules